version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: datawarehouse
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    ports:
      - "${db_port}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge